In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import statsmodels.tools as sm

In [4]:
x = pd.read_feather('created_data/final_transaction_cluster.feather')
y = x.cluster
x.drop(['cust_id','cluster'],inplace=True,axis=1)
x = sm.add_constant(x)
x.head(1)

const   income   age  num_cred_trans  num_save_trans  num_cheq_trans  \
0    1.0  50890.0  33.0            32.0            26.0            99.0   

   avg_cheq_amt  avg_save_amt  avg_cred_amt  money_gained  
0     -2.474646     18.550769     60.895625   -450.503333

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

logistic_regression = LogisticRegression()
logistic_regression.fit(x_train, y_train)
y_pred = logistic_regression.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)

print("accuracy: ", accuracy*100)

accuracy:  56.390977443609025


c:\Users\malco\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [7]:
logistic_regression.intercept_

array([-1.24068627e-04, -4.47788196e-05,  2.73942975e-05,  3.63425862e-05,
        1.05110563e-04])

In [8]:
logistic_regression.coef_

array([[-1.24068611e-04, -1.86310914e-05, -4.75407353e-03,
        -4.78118845e-03, -2.30247876e-03, -8.67242142e-03,
        -3.05326502e-04, -6.44952030e-04,  2.85653136e-03,
        -1.57510136e-03],
       [-4.47788129e-05,  6.91760119e-05, -8.51333340e-04,
        -1.28733562e-03, -1.60604986e-03, -1.67566151e-02,
         1.86253526e-03, -2.84635788e-03,  1.82725392e-03,
         4.15107267e-04],
       [ 2.73942939e-05,  4.22895692e-05,  5.68727075e-04,
         1.42584610e-03, -5.17578902e-03,  1.04349008e-02,
         1.39520187e-03, -3.34826109e-03, -4.23192745e-03,
        -1.52467076e-04],
       [ 3.63425814e-05, -9.74906458e-05, -4.19824189e-04,
        -1.07109238e-03,  1.39165662e-03, -3.18119209e-03,
         1.90648166e-04,  6.01464176e-04,  1.51825767e-03,
         1.09483461e-03],
       [ 1.05110549e-04,  4.65615618e-06,  5.45650398e-03,
         5.71377035e-03,  7.69266101e-03,  1.81753278e-02,
        -3.14305879e-03,  6.23810683e-03, -1.97011550e-03,
         2.

In [9]:
y_pred

array([4, 2, 4, 4, 1, 2, 4, 4, 4, 4, 4, 2, 0, 4, 4, 2, 4, 4, 4, 4, 4, 2,
       4, 1, 1, 0, 4, 4, 1, 4, 2, 3, 4, 1, 2, 4, 2, 4, 2, 0, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 3, 3, 4, 4, 4, 1, 4, 1, 4, 4, 0,
       1, 2, 0, 0, 0, 1, 4, 4, 2, 1, 1, 4, 2, 2, 2, 0, 4, 0, 4, 1, 4, 0,
       4, 4, 4, 4, 1, 4, 4, 1, 2, 4, 1, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2,
       2, 1, 4, 4, 1, 2, 4, 4, 2, 4, 4, 3, 0, 4, 4, 4, 0, 2, 3, 1, 2, 2,
       4])

In [10]:
coef = logistic_regression.coef_

z = np.dot(x_test, coef.T)

z += logistic_regression.intercept_

In [11]:
np.argmax(z,axis=1)

array([4, 2, 4, 4, 1, 2, 4, 4, 4, 4, 4, 2, 0, 4, 4, 2, 4, 4, 4, 4, 4, 2,
       4, 1, 1, 0, 4, 4, 1, 4, 2, 3, 4, 1, 2, 4, 2, 4, 2, 0, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 3, 3, 4, 4, 4, 1, 4, 1, 4, 4, 0,
       1, 2, 0, 0, 0, 1, 4, 4, 2, 1, 1, 4, 2, 2, 2, 0, 4, 0, 4, 1, 4, 0,
       4, 4, 4, 4, 1, 4, 4, 1, 2, 4, 1, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2,
       2, 1, 4, 4, 1, 2, 4, 4, 2, 4, 4, 3, 0, 4, 4, 4, 0, 2, 3, 1, 2, 2,
       4], dtype=int64)

In [12]:
z[0]

array([-1.05140549, -1.75047762,  1.12979081, -1.21480906,  2.88690136])

In [13]:
probs = 1 / (1 + np.exp(-z))
probs[0]

array([0.2589553 , 0.14798697, 0.75580029, 0.22885125, 0.94719511])

In [14]:
y_pred = np.argmax(probs, axis=1)
y_pred

array([4, 2, 4, 4, 1, 2, 4, 4, 4, 4, 4, 2, 0, 4, 4, 2, 4, 4, 4, 4, 4, 2,
       4, 1, 1, 0, 4, 4, 1, 4, 2, 3, 4, 1, 2, 4, 2, 4, 2, 0, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 3, 3, 4, 4, 4, 1, 4, 1, 4, 4, 0,
       1, 2, 0, 0, 0, 1, 4, 4, 2, 1, 1, 4, 2, 2, 2, 0, 4, 0, 4, 1, 4, 0,
       4, 4, 4, 4, 1, 4, 4, 1, 2, 4, 1, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2,
       2, 1, 4, 4, 1, 2, 4, 4, 2, 4, 4, 3, 0, 4, 4, 4, 0, 2, 3, 1, 2, 2,
       4], dtype=int64)

In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# load data
x = pd.read_feather('created_data/final_transaction_cluster.feather')
y = x.cluster
x.drop(['cust_id','cluster'],inplace=True,axis=1)

# split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

rand_forest = RandomForestClassifier().fit(x_train, y_train)

y_pred = rand_forest.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

print('accuracy: ' + str(accuracy*100) + '%')

accuracy: 90.97744360902256%


In [16]:
rand_forest.feature_importances_

array([0.06270882, 0.08313687, 0.03497778, 0.24729606, 0.23419928,
       0.106874  , 0.11485164, 0.01909426, 0.09686128])

In [17]:
y_pred

array([3, 2, 3, 2, 2, 4, 2, 3, 1, 4, 2, 2, 3, 4, 2, 4, 4, 1, 1, 3, 0, 0,
       3, 2, 1, 4, 4, 4, 0, 1, 1, 4, 4, 1, 3, 4, 4, 4, 4, 4, 2, 1, 3, 4,
       2, 3, 2, 2, 4, 2, 1, 2, 3, 4, 4, 4, 4, 2, 1, 3, 2, 2, 4, 2, 2, 4,
       2, 4, 2, 4, 2, 4, 4, 3, 2, 4, 4, 4, 2, 1, 4, 2, 3, 2, 4, 2, 2, 2,
       1, 4, 1, 4, 2, 4, 4, 2, 1, 2, 1, 4, 4, 4, 3, 3, 4, 4, 2, 2, 4, 2,
       4, 4, 2, 0, 0, 4, 1, 4, 2, 4, 4, 3, 4, 4, 3, 1, 0, 2, 1, 2, 2, 2,
       1])