In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [38]:
x = pd.read_feather('created_data/final_transaction_cluster.feather')
y = x.cluster
x.drop(['cust_id','cluster'],inplace=True,axis=1)
x.head(1)

income   age  num_cred_trans  num_save_trans  num_cheq_trans  \
0  50890.0  33.0            32.0            26.0            99.0   

   avg_cheq_amt  avg_save_amt  avg_cred_amt  money_gained  
0     -2.474646     18.550769     60.895625   -450.503333

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [62]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

logistic_regression = LogisticRegression()
logistic_regression.fit(x_train, y_train)
y_pred = logistic_regression.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)

print("accuracy: ", accuracy*100)

accuracy:  63.1578947368421


c:\Users\malco\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [57]:
logistic_regression.intercept_

array([-1.30011450e-04, -5.69493236e-05,  1.62085005e-05,  4.72936024e-05,
        1.23458671e-04])

In [59]:
logistic_regression.coef_

array([[-1.67415842e-05, -4.64011721e-03, -4.65598287e-03,
        -2.66269782e-03, -8.96894578e-03, -2.92500977e-05,
        -3.91248690e-04, -6.00441358e-03, -1.85215079e-03],
       [ 6.61608210e-05, -1.32811313e-03, -1.64645294e-03,
        -2.02660136e-03, -1.83829200e-02,  2.15103215e-03,
        -2.54949470e-03,  7.20708228e-03,  6.65964047e-04],
       [ 4.16723506e-05,  8.69312973e-05,  1.11398695e-03,
        -5.68987739e-03,  1.04996309e-02,  1.04839577e-03,
        -3.17002623e-03, -5.02699259e-04, -1.50352385e-04],
       [-8.24625881e-05, -4.14101014e-04, -1.24260119e-03,
         1.80025437e-03, -3.76876464e-03,  2.02894984e-04,
         8.80034192e-04,  1.97080364e-03,  1.39844775e-03],
       [-8.62899937e-06,  6.29540006e-03,  6.43105005e-03,
         8.57892220e-03,  2.06209995e-02, -3.37307280e-03,
         5.23073542e-03, -2.67077308e-03, -6.19086173e-05]])

In [65]:
y_pred

array([0, 4, 2, 1, 4, 1, 4, 4, 0, 1, 0, 1, 4, 4, 2, 2, 1, 1, 4, 4, 4, 4,
       2, 0, 4, 1, 1, 2, 1, 2, 4, 4, 0, 4, 4, 2, 1, 4, 4, 4, 4, 2, 4, 4,
       4, 4, 0, 4, 4, 2, 0, 4, 2, 4, 4, 1, 2, 3, 4, 1, 1, 4, 0, 0, 4, 4,
       4, 1, 0, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 1, 4, 4, 4, 2, 4,
       2, 3, 3, 4, 4, 1, 4, 0, 1, 2, 4, 4, 4, 4, 0, 0, 0, 4, 3, 4, 4, 4,
       4, 4, 4, 4, 1, 4, 1, 4, 4, 4, 3, 4, 4, 4, 4, 4, 1, 4, 4, 4, 0, 2,
       4])

In [96]:
coef = logistic_regression.coef_

z = np.dot(x_test, coef.T)

z += logistic_regression.intercept_

In [105]:
np.argmax(z,axis=1)

array([0, 4, 2, 1, 4, 1, 4, 4, 0, 1, 0, 1, 4, 4, 2, 2, 1, 1, 4, 4, 4, 4,
       2, 0, 4, 1, 1, 2, 1, 2, 4, 4, 0, 4, 4, 2, 1, 4, 4, 4, 4, 2, 4, 4,
       4, 4, 0, 4, 4, 2, 0, 4, 2, 4, 4, 1, 2, 3, 4, 1, 1, 4, 0, 0, 4, 4,
       4, 1, 0, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 1, 4, 4, 4, 2, 4,
       2, 3, 3, 4, 4, 1, 4, 0, 1, 2, 4, 4, 4, 4, 0, 0, 0, 4, 3, 4, 4, 4,
       4, 4, 4, 4, 1, 4, 1, 4, 4, 4, 3, 4, 4, 4, 4, 4, 1, 4, 4, 4, 0, 2,
       4], dtype=int64)

In [109]:
z[0]

array([ 5.259428  , -3.42102193,  2.6412508 , -7.38767275,  2.90801587])

In [107]:
probs = 1 / (1 + np.exp(-z))
probs[0]

array([9.94828605e-01, 3.16448979e-02, 9.33469686e-01, 6.18451744e-04,
       9.48241271e-01])

In [88]:
y_pred = np.argmax(probs, axis=1)
y_pred

array([0, 4, 2, 1, 4, 1, 4, 4, 0, 1, 0, 1, 4, 4, 2, 2, 1, 1, 4, 4, 4, 4,
       2, 0, 4, 1, 1, 2, 1, 2, 4, 4, 0, 4, 4, 2, 1, 4, 4, 4, 4, 2, 4, 4,
       4, 4, 0, 4, 4, 2, 0, 4, 2, 4, 4, 1, 2, 3, 4, 1, 1, 4, 0, 0, 4, 4,
       4, 1, 0, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4, 4, 4, 1, 4, 4, 4, 2, 4,
       2, 3, 3, 4, 4, 1, 4, 0, 1, 2, 4, 4, 4, 4, 0, 0, 0, 4, 3, 4, 4, 4,
       4, 4, 4, 4, 1, 4, 1, 4, 4, 4, 3, 4, 4, 4, 4, 4, 1, 4, 4, 4, 0, 2,
       4], dtype=int64)

In [42]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# load data
x = pd.read_feather('created_data/final_transaction_cluster.feather')
y = x.cluster
x.drop(['cust_id','cluster'],inplace=True,axis=1)

# split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

rand_forest = RandomForestClassifier().fit(x_train, y_train)

y_pred = rand_forest.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)

print('accuracy: ' + str(accuracy*100) + '%')

accuracy: 93.98496240601504%


In [43]:
rand_forest.feature_importances_

array([0.06004063, 0.08077949, 0.03625793, 0.27258364, 0.2359054 ,
       0.09451042, 0.08854979, 0.02118138, 0.11019132])

In [ ]:
y_pred

array([3, 4, 4, 4, 4, 1, 1, 2, 2, 3, 2, 4, 1, 1, 4, 2, 4, 1, 2, 4, 1, 4,
       3, 3, 4, 4, 2, 4, 2, 2, 4, 4, 4, 2, 4, 2, 3, 4, 2, 2, 3, 1, 1, 2,
       2, 4, 1, 2, 4, 2, 1, 2, 2, 2, 2, 0, 1, 3, 4, 1, 2, 4, 4, 4, 4, 1,
       4, 4, 4, 1, 4, 0, 2, 2, 2, 3, 4, 2, 4, 1, 1, 1, 0, 1, 3, 4, 2, 2,
       4, 4, 0, 2, 1, 2, 2, 4, 1, 0, 4, 1, 4, 0, 0, 1, 4, 2, 1, 4, 1, 4,
       4, 2, 2, 4, 1, 4, 2, 0, 1, 4, 2, 1, 2, 4, 4, 3, 2, 2, 1, 2, 4, 4,
       2])